baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CodenamedSuper'
theme = 'paige'

[languages.en]
languagecode = "en-us"
copyright = "(c) CodenamedSuper"
languagedirection = "ltr"
languagename = "English"
title = "title"
weight = 10

[languages.en.params.paige.site]
description = "subtitle"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[outputs]
home = ["atom", "html", "paige-search", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[pagination]
pagersize = 50

[params.paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true

[paige.pages.base_schema]
isAccessibleForFree = true
isFamilyFriendly = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true

[params.paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
